<?php
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * User login widget view script
 * 
 * @package    User
 */

// prepare form
$actionUrl = $this->url('user', array('action' => 'login'), true);
?>
<div class="well">
<h4><?php echo $this->translate('user_message_not_logged_on'); ?></h4>
<?php echo $this->showForm($this->form, $actionUrl, 'form-vertical'); ?>
</div>