<?php
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use User\Entity\UserEntity;

/**
 * User login widget view script
 * 
 * @package    User
 */

// set user entity
$user = $this->identity; /* @var $user UserEntity */

// prepare form
$actionUrl = $this->url('user', array('action' => 'logout'));
?>
<div class="well">
<h4><?php echo $this->translate('user_message_logged_on'); ?></h4>
<table style="width: 100%;" class="table table-data">
<tbody>
<tr>
<th><?php echo $this->translate('user_label_email'); ?>:</th>
<td><?php echo $user->getEmail(); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('user_label_name'); ?>:</th>
<td>
<?php echo $user->getFirstname(); ?> <?php echo $user->getLastname(); ?>
</td>
</tr>
</tbody>
</table>
<div class="pull-center">
<?php echo $this->showForm($this->form, $actionUrl, 'form-vertical'); ?>
</div>
</div>
