<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Kontakt');
$this->pageTitle('Sie haben eine Frage an uns?');

$url = $this->url('application', array(), array(), true);

echo $this->cmsContentBlock('application_about_contact', $url);
