<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Impressum');
$this->pageTitle('Impressum und rechtliche Hinweise');

$url = $this->url('application', array(), array(), true);

echo $this->cmsContentBlock('application_about_imprint', $url);
