<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * About us view script
 * 
 * @package    Application
 */

$this->headTitle('Über uns');
$this->pageTitle('Zend\Together - was ist das?');

$url = $this->url('application', array(), array(), true);
?>
<?php if ($this->getHelperPluginManager()->has('commentShowLinks')) : ?>
<?php echo $this->commentShowLinks($url); ?>
<?php endif; ?>
<?php echo $this->cmsContentBlock('application_about_index', $url); ?>
<?php if ($this->getHelperPluginManager()->has('commentShowComments')) : ?>
<?php echo $this->commentShowComments($url); ?>
<?php endif; ?>
