<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * Sessions view script
 * 
 * @package    Application
 */

$this->headTitle('application_head_sessions');

$url = $this->url('application', array(), array(), true);

echo $this->cmsContentBlock('application_about_sessions', $url);

