<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Tickets view script
 * 
 * @package    Application
 */

$this->headTitle('Tickets');
$this->pageTitle('Informationen zu den Tickets');

$url = $this->url('application', array(), array(), true);
?>
<?php echo $this->cmsContentBlock('application_about_tickets', $url); ?>
