<?php 
/**
 * Website Zend\Together
 *
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * Blog-Admin create view script
 * 
 * @package    Blog
 */

$this->headTitle('blog_head_create');
$this->pageTitle('blog_page_create');

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

$actionUrl = $this->url('blog-admin/action', array('action' => 'create'));

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
