<?php 
/**
 * Website Zend\Together
 *
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Blog-Admin update view script
 * 
 * @package    Blog
 */

$this->headTitle('Blogbeitrag bearbeiten');
$this->pageTitle('Einen bestehenden Blogbeitrag bearbeiten');

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

$actionUrl = $this->url('blog-admin/action', array(), array(), true);

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
