<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Cms\Module'                             => __DIR__ . '/Module.php',
  'Cms\Service\CmsServiceInterface'        => __DIR__ . '/src/Cms/Service/CmsServiceInterface.php',
  'Cms\Service\CmsService'                 => __DIR__ . '/src/Cms/Service/CmsService.php',
  'Cms\View\Helper\CmsContentBlockFactory' => __DIR__ . '/src/Cms/View/Helper/CmsContentBlockFactory.php',
  'Cms\View\Helper\CmsContentBlock'        => __DIR__ . '/src/Cms/View/Helper/CmsContentBlock.php',
  'Cms\Form\ContentBlockFormInterface'     => __DIR__ . '/src/Cms/Form/ContentBlockFormInterface.php',
  'Cms\Form\ContentBlockForm'              => __DIR__ . '/src/Cms/Form/ContentBlockForm.php',
  'Cms\Controller\CmsControllerFactory'    => __DIR__ . '/src/Cms/Controller/CmsControllerFactory.php',
  'Cms\Controller\CmsController'           => __DIR__ . '/src/Cms/Controller/CmsController.php',
);
