<?php 
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * User-Admin delete view script
 * 
 * @package    User
 */

$this->headTitle('user_head_delete');
$this->pageTitle('user_page_delete');

// set user entity
$user = $this->user; /* @var $user UserEntity */
$name = $user->getFirstname() . ' ' . $user->getLastname();

$actionUrl = $this->url('user-admin/action', array(), array(), true);
?>
<table class="table table-data">
<tbody>
<tr>
<th><?php echo $this->translate('user_label_name'); ?>:</th>
<td><?php echo $name; ?></td>
</tr>
<tr>
<th><?php echo $this->translate('user_label_email'); ?>: &nbsp;</th>
<td><?php echo $user->getEmail(); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('user_label_role'); ?>:</th>
<td><?php echo $this->translate($user->getRoleName()); ?></td>
</tr>
</tbody>
</table>
<?php echo $this->showForm($this->form, $actionUrl, 'form-horizontal'); ?>
