<?php
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use User\Entity\UserEntity;

/**
 * User-Admin index view script
 *
 * @package    User
 */

$this->headTitle('user_head_admin');
$this->pageTitle('user_page_admin');
?>
<table class="table table-striped table-bordered table-hover table-condensed">
<thead>
<tr>
<th><?php echo $this->translate('user_label_email'); ?></th>
<th><?php echo $this->translate('user_label_name'); ?></th>
<th><?php echo $this->translate('user_label_role'); ?></th>
<th width="180">&nbsp;</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->userList as $user) : /* @var $user UserEntity */ ?>
<?php
    $urlEdit = $this->url('user-admin/action', array('action' => 'update', 'id' => $user->getId()), true);
    $urlDelete = $this->url('user-admin/action', array('action' => 'delete', 'id' => $user->getId()), true);
?>
<tr>
<td><?php echo $user->getEmail(); ?></td>
<td><?php echo $user->getFirstname(); ?> <?php echo $user->getLastname(); ?></td>
<td><?php echo $this->translate($user->getRoleName()); ?></td>
<td>
<a href="<?php echo $urlEdit; ?>" class="btn"><?php echo $this->translate('user_button_update'); ?></a>
<a href="<?php echo $urlDelete; ?>" class="btn"><?php echo $this->translate('user_button_delete'); ?></a>
</td>
</tr>
<?php endforeach; ?>
</tbody>
</table>
<?php
echo $this->paginationControl(
    $this->userList, 'Sliding', 'pagination/sliding',
    array('route' => 'user-admin/page')
);
?>
