<?php 
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * User-Admin update view script
 * 
 * @package    User
 */

$this->headTitle('user_head_update');
$this->pageTitle('user_page_update');

$actionUrl = $this->url('user-admin/action', array(), array(), true);

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
