<?php 
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * User forbidden view script
 * 
 * @package    User
 */

$this->headTitle('user_head_forbidden');
$this->pageTitle('user_page_forbidden');

?>
<p><?php echo $this->translate('user_message_auth_forbidden'); ?></p>

<p class="pull-center"><a href="/" class="btn"><?php echo $this->translate('application_button_home') ?></a></p>
