<?php 
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * User forbidden view script
 * 
 * @package    User
 */

$this->headTitle('Zugriff nicht erlaubt');
$this->pageTitle('Du kommst hier nicht rein!');
?>
<p>Leider dürfen Sie diese Seite nicht aufrufen. Da sind uns echt die Hände gebunden und wir dürfen keine Ausnahmen machen.</p>

<p class="pull-center"><a href="/" class="btn">Zur Startseite</a></p>
