<?php 
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use User\Entity\UserEntity;

/**
 * User index view script
 * 
 * @package    User
 */

$this->headTitle('user_head_index');
$this->pageTitle('user_page_index');

// set user entity
$user = $this->identity; /* @var $user UserEntity */
$name = $user->getFirstname() . ' ' . $user->getLastname();

?>
<table class="table table-data">
<tbody>
<tr>
<th><?php echo $this->translate('user_label_email'); ?>:</th>
<td><?php echo $user->getEmail(); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('user_label_name'); ?>:</th>
<td><?php echo $name; ?></td>
</tr>
<tr>
<th><?php echo $this->translate('user_label_role'); ?>:</th>
<td><?php echo $this->translate($user->getRoleName()); ?></td>
</tr>
<tr>
<th>&nbsp;</th>
<td>
<?php if ($this->userIsAllowed('user-admin')): ?>
<?php $url = $this->url('user-admin', array(), true); ?>
<a href="<?php echo $url; ?>" class="btn"><?php echo $this->translate('user_button_admin') ?></a>
<?php endif; ?>
<a href="/" class="btn"><?php echo $this->translate('application_button_home') ?></a>
</td>
</tr>
</tbody>
</table>
