<?php 
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use User\Entity\UserEntity;

/**
 * User index view script
 * 
 * @package    User
 */

// set user entity
$user = $this->identity; /* @var $user UserEntity */
$name = $user->getFirstname() . ' ' . $user->getLastname();

$this->headTitle('Benutzer anzeigen');
$this->pageTitle('Schön, dass Sie da sind, ' . $name);
?>
<table class="table table-data">
<tbody>
<tr>
<th>E-Mail:</th>
<td><?php echo $user->getEmail(); ?></td>
</tr>
<tr>
<th>Name:</th>
<td><?php echo $name; ?></td>
</tr>
<tr>
<th>Rolle:</th>
<td><?php echo $user->getRoleName(); ?></td>
</tr>
<tr>
<th>&nbsp;</th>
<td>
<?php if ($this->userIsAllowed('user-admin')): ?>
<?php $url = $this->url('user-admin'); ?>
<a href="<?php echo $url; ?>" class="btn">Benutzer verwalten</a>
<?php endif; ?>
<a href="/" class="btn">Zurück zur Homepage</a>
</td>
</tr>
</tbody>
</table>
