<?php 
/**
 * Website Zend\Together
 *
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * User register view script
 * 
 * @package    User
 */

$this->headTitle('user_head_register');
$this->pageTitle('user_page_register');

$actionUrl = $this->url('user', array('action' => 'register'));

echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
?>
<hr />
<h3><?php echo $this->translate('user_message_registration') ?></h3>
<?php $url = $this->url('user', array('action' => 'login'))?>
<a href="<?php echo $url; ?>" class="btn"><?php echo $this->translate('user_button_login') ?></a>