<?php
/**
 * Website Zend\Together
 *
 * @package    Comment
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use Comment\Entity\CommentEntity;
use Zend\View\Helper\Gravatar;

/**
 * Comment show comments list and form view script
 * 
 * @package    Comment
 */

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);
?>
<hr />
<div id="comments">
<h3><?php echo $this->translate('comment_page_list') ?></h3>
<?php if ($this->commentList->count() > 0) :?>
<?php foreach($this->commentList as $comment) :  /* @var $comment CommentEntity */ ?>
<hr />
<div class="pull-left">
<?php 
    echo $this->gravatar(
        $comment->getEmail(), 
        array('imgSize' => 50, 'defaultImg' => Gravatar::DEFAULT_IDENTICON), 
        array('class' => 'gravatar', 'title' => $comment->getName())
    );
?>
</div>
<blockquote id="comment-<?php echo $comment->getId(); ?>">
<?php echo $comment->getMessage();?>
<small>
<i class="icon-user"></i> <?php echo $comment->getName();?>
&nbsp;|&nbsp;
<i class="icon-calendar"></i> <?php echo $this->date($comment->getCdate()); ?>
</small>
</blockquote>
<?php endforeach; ?>
<?php else: ?>
<p><?php echo $this->translate('comment_message_no_entries') ?></p>
<?php endif; ?>
</div>
<hr />
<div id="comment-form">
<h3><?php echo $this->translate('comment_page_create') ?></h3>
<p><?php echo $this->translate('comment_message_notes') ?></p>
<br />
<?php 
$actionUrl = $this->url('comment', array('action' => 'add'), true);
echo $this->showForm($this->commentForm, $actionUrl, 'form-horizontal');
?>
</div>
