<?php
/**
 * Website Zend\Together
 *
 * @package    Comment
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Comment show links list and form view script
 * 
 * @package    Comment
 */
?>
<p>
<em>
<i class="icon-comment"></i> 
<a href="<?php echo $this->commentUrl;?>#comments">
<?php $text = $this->commentCount == 1 ? 'Kommentar' : 'Kommentare'; ?>
<?php echo $this->commentCount; ?> <?php echo $text; ?></a>
&nbsp;|&nbsp;
<i class="icon-pencil"></i> 
<a href="<?php echo $this->commentUrl;?>#comment-form">
Kommentar schreiben</a>
</em>
</p>
