<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Listing 22.13 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.13');
$this->pageTitle('Listing 22.13');
?>
<h3>View-Helper <code>GetOrder</code> holt Bestelldaten</h3>
<pre>
&lt;?php
namespace Shop\View\Helper;

use Shop\Entity\OrderEntityInterface;
use Shop\Service\OrderServiceInterface;
use Zend\View\Helper\AbstractHelper;

class GetOrder extends AbstractHelper
{
    protected $orderService;

    public function __construct(OrderServiceInterface $orderService)
    {
        $this->setOrderService($orderService);
    }

    public function setOrderService(OrderServiceInterface $orderService = null)
    {
        $this->orderService = $orderService;
        return $this;
    }
    
    public function getOrderService()
    {
        return $this->orderService;
    }
    
    public function __invoke($id)
    {
        return $this->getOrderService()->fetchSingleById($id);
    }
}
</pre>
