<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Listing 22.11 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.11');
$this->pageTitle('Listing 22.11');
?>
<h3>View-Skript <code>small-basket.phtml</code> gibt gekürzten Warenkorb aus</h3>
<pre>
&lt;?php
$basket = $this-&gt;basket;
?&gt;
&lt;div class="well"&gt;
&lt;h4&gt;Warenkorb&lt;/h4&gt;
&lt;?php if ($basket-&gt;isEmpty()) : ?&gt;
&lt;p&gt;Ihr Warenkorb ist leer.&lt;/p&gt;
&lt;?php else : ?&gt;
&lt;p&gt;
Sie haben &lt;?php echo $basket-&gt;getCount() ?&gt; Artikel für 
&lt;?php echo $this-&gt;currencyFormat($basket-&gt;getTotal()); ?&gt; im Warenkorb.
&lt;/p&gt;
&lt;?php $basketUrl = $this-&gt;url('shop/basket'); ?&gt;
&lt;p&gt;&lt;a href="&lt;?php echo $basketUrl; ?&gt;" class="btn"&gt;Warenkorb anzeigen&lt;/a&gt;&lt;/p&gt;
&lt;?php endif; ?&gt;
&lt;/div&gt;
</pre>
