<?php 
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Listing 22.15 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 22.15');
$this->pageTitle('Listing 22.15');
?>
<h3>View-Skript <code>index.phtml</code> zur Darstellung des Warenkorbs</h3>
<pre>
&lt;?php
$this-&gt;headTitle('Warenkorb');
$this-&gt;pageTitle('Ihr Warenkorb');

$basket = $this-&gt;basket; /* @var $basket BasketEntity */

echo $this-&gt;shopShowBasket('full');
?&gt;
&lt;?php if (!$basket-&gt;isEmpty()) : ?&gt;
&lt;?php if ($this-&gt;userIsAllowed('order', 'create')): ?&gt;
&lt;?php $urlOrder = $this-&gt;url('shop/order/action', array('action' =&gt; 'create')); ?&gt;
&lt;h4&gt;Sie sind angemeldet und können nun bestellen.&lt;/h4&gt; 
&lt;p&gt;
&lt;a href="&lt;?php echo $urlOrder; ?&gt;" class="btn"&gt;Bestellung ausführen&lt;/a&gt;
&lt;/p&gt;
&lt;?php else: ?&gt;
&lt;?php $urlLogin    = $this-&gt;url('user', array('action' =&gt; 'login')); ?&gt;
&lt;?php $urlRegister = $this-&gt;url('user', array('action' =&gt; 'register')); ?&gt;
&lt;h4&gt;Sie sind nicht angemeldet.&lt;/h4&gt; 
&lt;p&gt;
&lt;a href="&lt;?php echo $urlLogin; ?&gt;" class="btn"&gt;Anmelden&lt;/a&gt; 
&lt;a href="&lt;?php echo $urlRegister; ?&gt;" class="btn"&gt;Jetzt registrieren&lt;/a&gt;
&lt;/p&gt;
&lt;?php endif; ?&gt;
&lt;?php endif; ?&gt;
</pre>
