<?php
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Footer view script
 * 
 * @package    Application
 */
?>
<footer>
<div class="container">
<div class="row">
<div class="span3">
<h4>Service</h4>
<ul class="unstyled">
<li><a href="<?php echo $this->url('application', array('controller' => 'about'))?>">Über uns</a></li>
<li><a href="<?php echo $this->url('application', array('controller' => 'about', 'action' => 'team'))?>">Team</a></li>
<li><a href="<?php echo $this->url('application', array('controller' => 'about', 'action' => 'contact'))?>">Kontakt</a></li>
<li><a href="<?php echo $this->url('application', array('controller' => 'about', 'action' => 'imprint'))?>">Impressum</a></li>
</ul>
</div>
<div class="span3">
<h4>Links</h4>
<ul class="unstyled">
<li><a href="#" target="_blank">###########</a></li>
<li><a href="#" target="_blank">###########</a></li>
<li><a href="#" target="_blank">###########</a></li>
<li><a href="#" target="_blank">###########</a></li>
</ul>
</div>
<div class="span3">
<h4>Social Media</h4>
<ul class="unstyled">
<li><i class="icon-rss"></i>RSS Feed</li>
<li><i class="icon-facebook"></i>Facebook Fanseite</li>
<li><i class="icon-google-plus"></i>Google+ Seite</li>
<li><i class="icon-twitter"></i>Twitter</li>
</ul>
</div>
<div class="span3">
<h4>Zend\Together wird präsentiert von</h4>
<img src="/img/luigis-pizza-logo-footer.gif" alt="Zend\Together" />
</div>
</div>
</div>
</footer>
<br />
<br />