<?php
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * Header view script
 *
 * @package    Application
 */

?>
<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
<a class="brand" href="/"><?php echo $this->translate('application_menu_index'); ?></a>
<div class="nav-collapse">
<?php
$this->navigation('navigation')->menu()->setUlClass('nav navbar-nav');
echo $this->bootstrapMenu($this->navigation('navigation')->menu()->renderMenu(null, array('maxDepth' => 1)));
?>
</div>
<ul class="nav pull-right">
    <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo $this->translate('application_menu_language'); ?> <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li <?php if ($this->lang == 'de') { echo 'class="active"'; } ?>>
                <a href="<?php echo $this->url(null, array('lang' => 'de'), true); ?>"><?php echo $this->translate('application_menu_german'); ?></a>
            </li>
            <li <?php if ($this->lang == 'en') { echo 'class="active"'; } ?>>
                <a href="<?php echo $this->url(null, array('lang' => 'en'), true); ?>"><?php echo $this->translate('application_menu_english'); ?></a>
            </li>
        </ul>
    </li>
</ul>
</div>
</div>
</div>
