<?php
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * Header view script
 *
 * @package    Application
 */

?>
<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
<a class="brand" href="/"><?php echo $this->translate('application_menu_index'); ?></a>
<div class="nav-collapse">
<?php
$this->navigation('navigation')->menu()->setUlClass('nav navbar-nav');
echo $this->bootstrapMenu($this->navigation('navigation')->menu()->renderMenu(null, array('maxDepth' => 1)));
?>
</div>
</div>
</div>
</div>
