<?php
/**
 * Website Zend\Together
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * Header view script
 * 
 * @package    Application
 */

?>
<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
<a class="brand" href="/">
<img src="/img/luigis-pizza-logo-menu.gif" alt="Zend\Together" />
</a>
<div class="nav-collapse">
<?php 
$this->navigation('navigation')->menu()->setUlClass('nav');
echo $this->navigation('navigation')->menu()->renderMenu(
    null, array('maxDepth' => 0)
);
?>
</div>
</div>
</div>
</div>
