<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Blog\Module'                            => __DIR__ . '/Module.php',
  'Blog\Filter\BlogFilter'                 => __DIR__ . '/src/Blog/Filter/BlogFilter.php',
  'Blog\Service\BlogServiceInterface'      => __DIR__ . '/src/Blog/Service/BlogServiceInterface.php',
  'Blog\Service\BlogService'               => __DIR__ . '/src/Blog/Service/BlogService.php',
  'Blog\Service\BlogServiceFactory'        => __DIR__ . '/src/Blog/Service/BlogServiceFactory.php',
  'Blog\Table\BlogTable'                   => __DIR__ . '/src/Blog/Table/BlogTable.php',
  'Blog\Table\BlogTableFactory'            => __DIR__ . '/src/Blog/Table/BlogTableFactory.php',
  'Blog\Table\BlogTableInterface'          => __DIR__ . '/src/Blog/Table/BlogTableInterface.php',
  'Blog\Entity\BlogEntityInterface'        => __DIR__ . '/src/Blog/Entity/BlogEntityInterface.php',
  'Blog\Entity\BlogEntity'                 => __DIR__ . '/src/Blog/Entity/BlogEntity.php',
  'Blog\Form\BlogFormInterface'            => __DIR__ . '/src/Blog/Form/BlogFormInterface.php',
  'Blog\Form\CreateFormFactory'            => __DIR__ . '/src/Blog/Form/CreateFormFactory.php',
  'Blog\Form\DeleteFormFactory'            => __DIR__ . '/src/Blog/Form/DeleteFormFactory.php',
  'Blog\Form\BlogForm'                     => __DIR__ . '/src/Blog/Form/BlogForm.php',
  'Blog\Form\UpdateFormFactory'            => __DIR__ . '/src/Blog/Form/UpdateFormFactory.php',
  'Blog\Controller\BlogController'         => __DIR__ . '/src/Blog/Controller/BlogController.php',
  'Blog\Controller\AdminController'        => __DIR__ . '/src/Blog/Controller/AdminController.php',
  'Blog\Controller\BlogControllerFactory'  => __DIR__ . '/src/Blog/Controller/BlogControllerFactory.php',
  'Blog\Controller\AdminControllerFactory' => __DIR__ . '/src/Blog/Controller/AdminControllerFactory.php',
);
