<?php 
/**
 * Website Zend\Together
 *
 * @package    Blog
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use Blog\Entity\BlogEntity;

/**
 * Blog index view script
 * 
 * @package    Blog
 */

$this->headTitle('blog_head_index');
$this->pageTitle('blog_page_index');
?>
<?php foreach ($this->blogList as $blog) : /* @var $blog BlogEntity */ ?>
<?php
$urlShow   = $this->url('blog/action', array('url' => $blog->getUrl()));
$urlEdit   = $this->url(
    'blog-admin/action', array('action' => 'update', 'id' => $blog->getId())
);
$urlDelete = $this->url(
    'blog-admin/action', array('action' => 'delete', 'id' => $blog->getId())
);
?>
<h3><a href="<?php echo $urlShow; ?>"><?php echo $blog->getTitle(); ?></a></h3>
<div class="clearfix">
<?php if ($this->getHelperPluginManager()->has('commentShowLinks')) : ?>
<?php echo $this->commentShowLinks($urlShow); ?>
<?php endif; ?>
<?php echo $blog->getTeaser(); ?>
<p><em><?php echo $this->translate('blog_label_date'); ?>: <?php echo $this->date($blog->getCdate()); ?></em></p>
<p>
<a href="<?php echo $urlShow; ?>" class="btn"><?php echo $this->translate('blog_button_read'); ?></a>
<?php if ($this->userIsAllowed('blog-admin')): ?>
<a href="<?php echo $urlEdit; ?>" class="btn"><?php echo $this->translate('blog_button_update'); ?></a>
<a href="<?php echo $urlDelete; ?>" class="btn"><?php echo $this->translate('blog_button_delete'); ?></a>
<?php endif; ?>
</p>
</div>
<hr />
<?php endforeach; ?>
<?php
echo $this->paginationControl(
    $this->blogList, 'Sliding', 'pagination/sliding', 
    array('route' => 'blog/page')
);
?>
<?php if ($this->userIsAllowed('blog-admin')): ?>
<p class="pull-center">
<?php $url = $this->url('blog-admin'); ?>
<a href="<?php echo $url; ?>" class="btn"><?php echo $this->translate('blog_button_admin'); ?></a>
</p>
<?php endif; ?>

