<?php
/**
 * Website Zend\Together
 *
 * @package    Comment
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use Comment\Entity\CommentEntity;

/**
 * Comment-Admin show view script
 *
 * @package    Comment
 */

$this->headTitle('comment_head_show');
$this->pageTitle('comment_page_show');

// set comment entity
$comment = $this->comment; /* @var $comment CommentEntity */

// get id
$id = $comment->getId();

// set show url
$urlComment = $comment->getUrl();
?>
<table class="table table-data">
<tbody>
<tr>
<th><?php echo $this->translate('comment_label_date'); ?></th>
<td><?php echo $this->date($comment->getCdate()); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('comment_label_url'); ?></th>
<td><a href="<?php echo $urlComment; ?>"><?php echo $urlComment; ?></a></td>
</tr>
<tr>
<th><?php echo $this->translate('comment_label_status'); ?></th>
<td><?php echo $this->translate($comment->getStatusName()); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('comment_label_email'); ?></th>
<td><?php echo $comment->getEmail(); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('comment_label_name'); ?></th>
<td><?php echo $comment->getName(); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('comment_label_spamclass'); ?></th>
<td><?php echo $this->spamCheck()->classify($comment->getFulltext()); ?></td>
</tr>
<tr>
<th><?php echo $this->translate('comment_label_message'); ?></th>
<td><?php echo $comment->getMessage(); ?></td>
</tr>
</tbody>
</table>
<div class="form-horizontal">
<div class="form-actions">
<?php if ($comment->getStatus() == 'new') : ?>
    <?php
        $urlSpam = $this->url('comment-admin/action', array('action' => 'spam', 'id' => $id), true);
        $urlHam  = $this->url('comment-admin/action', array('action' => 'ham', 'id' => $id), true);
    ?>
    <a href="<?php echo $urlSpam; ?>" class="btn"><i class="icon-thumbs-down"></i> <?php echo $this->translate('comment_button_spam');?></a>
    <a href="<?php echo $urlHam; ?>" class="btn"><i class="icon-thumbs-up"></i> <?php echo $this->translate('comment_button_ham');?></a>
<?php elseif ($comment->getStatus() == 'approved'): ?>
    <?php
    $urlNoHam  = $this->url('comment-admin/action', array('action' => 'no-ham', 'id' => $id), true);
    ?>
    <a href="<?php echo $urlNoHam; ?>" class="btn"><i class="icon-thumbs-down"></i> <?php echo $this->translate('comment_button_noham');?></a>
<?php else: ?>
    <?php
    $urlNoSpam  = $this->url('comment-admin/action', array('action' => 'no-spam', 'id' => $id), true);
    ?>
    <a href="<?php echo $urlNoSpam; ?>" class="btn"><i class="icon-thumbs-up"></i> <?php echo $this->translate('comment_button_nospam');?></a>
<?php endif; ?>
<?php
$urlCancel  = $this->url('comment-admin', array(), true);
$urlEdit    = $this->url('comment-admin/action', array('action' => 'update', 'id' => $id), true);
$urlDelete  = $this->url('comment-admin/action', array('action' => 'delete', 'id' => $id), true);
?>
<a href="<?php echo $urlEdit; ?>" class="btn"><i class="icon-pencil"></i> <?php echo $this->translate('comment_button_update');?></a>
<a href="<?php echo $urlDelete; ?>" class="btn"><i class="icon-trash"></i> <?php echo $this->translate('comment_button_delete');?></a>
<a href="<?php echo $urlCancel; ?>" class="btn"><i class="icon-ban-circle"></i> <?php echo $this->translate('comment_button_cancel');?></a>
</div>
</div>
