<?php 
/**
 * Website Zend\Together
 *
 * @package    Comment
 * @author     Ralf Eggert <r.eggert@travello.de>
 * * @link       http://www.zf-together.com
 */

/**
 * namespace definition and usage
 */
use Comment\Entity\CommentEntity;

/**
 * Comment-Admin update view script
 * 
 * @package    Comment
 */

$this->headTitle('Kommentar bearbeiten');
$this->pageTitle('Einen Kommentar bearbeiten');

$this->headScript()->appendFile(
    $this->basePath() . '/js/ckeditor/ckeditor.js', 'text/javascript'
);

// set comment entity
$comment = $this->comment; /* @var $comment CommentEntity */

$url = $comment->getUrl();
?>
<table class="table table-data">
<tbody>
<tr>
<th>Datum &nbsp;</th>
<td><?php echo $this->date($comment->getCdate()); ?></td>
</tr>
<tr>
<th>Url &nbsp;</th>
<td><a href="<?php echo $url; ?>"><?php echo $url; ?></a></td>
</tr>
</tbody>
</table>
<?php 
$actionUrl = $this->url('comment-admin/action', array(), array(), true);
echo $this->showForm($this->form, $actionUrl, 'form-horizontal');
